{
 "title": "Zabbix with template Linux servers (share)",
 "description": "Zabbix monitoring overview Linux servers",
 "tags": [
  "Zabbix",
  "Version 4.4.0",
  "linux server"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": "*" },
   { "name": "host", "label": "Host", "query": "$group.*" },
   { "name": "app", "label": "App", "query": "$group.$host.*" },
   { "name": "appnet", "label": "Network Interface", "query": "$group.$host.*" },
   { "name": "netif", "query": "$group.$host.$appnet.*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "content": "<h1 style=\"text-align: center;\"><img src=\"https://images.esp-online.com/thumbnails/aws_solution_list_thumbnail/2614/9455/9402/ZABBIX_LOGO.jpg\" alt=\"\" width=\"191\" height=\"50\" /></h1>\n<h1 style=\"text-align: center;\"><span style=\"color: #ffffff;\"><strong>Trangnth</strong></span></h1>"
  },
  {
   "title": "Server uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix Agent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "$app" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Zabbix agent ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of CPUs" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of processes" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memory utilization" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "System load 15 min",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Load average (15m avg)" },
     "minSeverity": 3,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Space utilization in % for /",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystem /" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/: Space utilization" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of logged in users",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of logged in users" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of running processes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of running processes" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/^CPU/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix Server Events in Group Linux servers",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": {
    "0": { "refId": "A" },
    "Zabbix-1": {
     "application": { "filter": "" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "title": "Network traffic on $netif",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "$app" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$netif" },
     "minSeverity": 3,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes", "label": "Memória" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix Server Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Zabbix server" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "100" ],
       "text": "scale(100)"
      }
     ],
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": {
      "filter": "Number of processed values per second"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Zabbix server" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "SVMGBZABPRD" },
     "item": { "filter": "Zabbix queue" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix Service Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Zabbix server" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Zabbix busy housekeeper in %" ],
       "text": "setAlias(Zabbix busy housekeeper in %)"
      }
     ],
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": {
      "filter": "Utilization of housekeeper internal processes, in %"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Zabbix server" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Zabbix busy trapper in %" ],
       "text": "setAlias(Zabbix busy trapper in %)"
      }
     ],
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "SVMGBZABPRD" },
     "item": {
      "filter": "Zabbix busy trapper processes, in %"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Zabbix server" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Zabbix busy alert manager in %" ],
       "text": "setAlias(Zabbix busy alert manager in %)"
      }
     ],
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "SVMGBZABPRD" },
     "item": {
      "filter": "Zabbix busy alert manager processes, in %"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Zabbix server" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "Zabbix busy history syncer in %"
       ],
       "text": "setAlias(Zabbix busy history syncer in %)"
      }
     ],
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "SVMGBZABPRD" },
     "item": {
      "filter": "Zabbix busy history syncer processes, in %"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Processor load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Load average .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "SVMGBZABPRD" },
     "item": {
      "filter": "Processor load (15 min average per core)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "SVMGBZABPRD" },
     "item": {
      "filter": "Processor load (5 min average per core)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}