{
 "title": "Monitoring VMs via Libvirt - v2",
 "description": "Monitoring VMs on OpenStack or KVM via Libvirt",
 "tags": [
  "openstack",
  "libvirt",
  "kvm"
 ],
 "time": { "from": "2020-05-27T04:24:12.105Z", "to": "2020-05-27T09:08:28.683Z" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "compute", "query": "collectd.*" },
   { "name": "uuid", "query": "collectd.$compute.*" },
   { "name": "virt", "query": "collectd.$compute.$uuid.*" },
   {
    "name": "interface",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "diskrw",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "diskops",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "vcpu",
    "query": "collectd.$compute.$uuid.$virt.*"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "content": "<br><br><br>\n<a href=\"https://www.mobifone.vn/\" ><h1 style=\"text-align: center;\"><img width=\"auto\" height=\"auto\" src=https://i.imgur.com/ZnwAO1W.png></h1></a>\n<br>\n\n\n\n\n\n"
  },
  {
   "title": "CPU used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasSub(scale(divideSeries(#B, #C), 100), '^scale\\(divideSeries\\((.*)\\.(.*)\\.(.*)\\.virt_cpu_total(.*)*', '\\3')",
     "targetFull": "aliasSub(scale(divideSeries(collectd.$compute.$uuid.$virt.virt_cpu_total, scale(countSeries(collectd.$compute.$uuid.$virt.virt_vcpu-*), 1000000000)), 100), '^scale\\(divideSeries\\((.*)\\.(.*)\\.(.*)\\.virt_cpu_total(.*)*', '\\3')"
    }
   ]
  },
  {
   "title": "Ram Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByNode(scale(#A, 1e-9), 3)",
     "targetFull": "aliasByNode(scale(collectd.$compute.$uuid.$virt.memory-unused, 1e-9), 3)"
    }
   ]
  },
  {
   "title": "DISK IOPS $uuid",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskops.read, 'read')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskops.write, 'write')"
    }
   ]
  },
  {
   "title": "Network $uuid",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$interface.tx, 'Data Out')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$interface.rx, 'Data In')"
    }
   ]
  },
  {
   "title": "DISK R/W $uuid",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskrw.read, 'read')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskrw.write, 'write')"
    }
   ]
  }
 ]
}