{
 "title": "Dashboard VMs overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "compute", "query": "collectd.*" },
   { "name": "uuid", "query": "collectd.$compute.*" },
   { "name": "virt", "query": "collectd.$compute.$uuid.*" },
   {
    "name": "if_octets",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "if_octets_rx",
    "query": "collectd.$compute.$uuid.$virt.$if_octets.*"
   },
   {
    "name": "if_octets_tx",
    "query": "collectd.$compute.$uuid.$virt.$if_octets.*"
   },
   {
    "name": "disk_octets",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "disk_octets_read",
    "query": "collectd.$compute.$uuid.$virt.$disk_octets.*"
   },
   {
    "name": "disk_octets_write",
    "query": "collectd.$compute.$uuid.$virt.$disk_octets.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk I/O Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$compute.$uuid.$virt.$disk_octets.$disk_octets_read, '^collectd\\.(.*)\\.(.*)\\.(.*)\\.disk_octets-(.*)\\.read', '\\4 \\2')"
    }
   ]
  },
  {
   "title": "Disk I/O Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$compute.$uuid.$virt.$disk_octets.$disk_octets_write, '^collectd\\.(.*)\\.(.*)\\.(.*)\\.disk_octets-(.*)\\.write', '\\4 \\2')"
    }
   ]
  },
  {
   "title": "Bandwidth Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$compute.$uuid.$virt.$if_octets.$if_octets_tx, 5, 2)"
    }
   ]
  },
  {
   "title": "Bandwidth In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$compute.$uuid.$virt.$if_octets.$if_octets_rx, 5, 2)"
    }
   ]
  }
 ]
}