{
 "title": "Dashboard overview Compute",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "collectd.*" },
   { "name": "server", "query": "collectd.$host.*" },
   { "name": "cpu", "query": "collectd.$host.$server.*" },
   { "name": "df", "query": "collectd.$host.$server.*" },
   { "name": "df_used", "query": "collectd.$host.$server.$df.*" },
   { "name": "disk", "query": "collectd.$host.$server.*" },
   { "name": "disk_octets", "query": "collectd.$host.$server.$disk.*" },
   {
    "name": "disk_octets_read",
    "query": "collectd.$host.$server.$disk.$disk_octets.*"
   },
   {
    "name": "disk_octets_write",
    "query": "collectd.$host.$server.$disk.$disk_octets.*"
   },
   { "name": "interface", "query": "collectd.$host.$server.*" },
   {
    "name": "if_octets",
    "query": "collectd.$host.$server.$interface.*"
   },
   {
    "name": "if_octets_rx",
    "query": "collectd.$host.$server.$interface.$if_octets.*"
   },
   {
    "name": "if_octets_tx",
    "query": "collectd.$host.$server.$interface.$if_octets.*"
   },
   { "name": "memory", "query": "collectd.$host.$server.*" },
   { "name": "swap", "query": "collectd.$host.$server.*.*" }
  ]
 },
 "panels": [
  {
   "title": "CPU_USER",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(collectd.$host.$server.$cpu.cpu-user, true), 3)"
    }
   ]
  },
  {
   "title": "CPU_SYSTEM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(collectd.$host.$server.$cpu.cpu-system, true), 3)"
    }
   ]
  },
  {
   "title": "Disk I/O Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.$server.$disk.$disk_octets.$disk_octets_read, 3)"
    }
   ]
  },
  {
   "title": "Disk I/O Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.$server.$disk.$disk_octets.$disk_octets_write, 3)"
    }
   ]
  },
  {
   "title": "BW In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.$server.$interface.$if_octets.$if_octets_rx, 3)"
    }
   ]
  },
  {
   "title": "BW out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.$server.$interface.$if_octets.$if_octets_tx, 3)"
    }
   ]
  },
  {
   "title": "df used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.$server.$df.$df_used, 3)"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$host.$server.$memory.memory-used, 'memory_used')"
    }
   ]
  }
 ]
}