{
 "title": "VMs",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "compute", "query": "collectd.*" },
   { "name": "uuid", "query": "collectd.$compute.*" },
   { "name": "virt", "query": "collectd.$compute.$uuid.*" },
   {
    "name": "interface",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "diskrw",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "diskops",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "vcpu",
    "query": "collectd.$compute.$uuid.$virt.*"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU used $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(collectd.$compute.$uuid.$virt.percent-virt_cpu_total, 'CPU USED')"
    }
   ]
  },
  {
   "title": "Network $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$interface.tx, 'Data Out')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$interface.rx, 'Data In')"
    }
   ]
  },
  {
   "title": "Ram Free $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.memory-unused, 'RAM FREE')"
    }
   ]
  },
  {
   "title": "DISK IOPS $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskops.read, 'read')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskops.write, 'write')"
    }
   ]
  },
  {
   "title": "DISK R/W $uuid",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskrw.read, 'read')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskrw.write, 'write')"
    }
   ]
  }
 ]
}