{
 "title": "Dashboard overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "collectd.*" },
   { "name": "server", "query": "collectd.$host.*" },
   { "name": "metric", "query": "collectd.$host.$server.*" },
   { "name": "cpu", "query": "collectd.$host.$server.*" },
   { "name": "df", "query": "collectd.$host.$server.*" },
   { "name": "disk", "query": "collectd.$host.$server.*" },
   { "name": "interface", "query": "collectd.$host.$server.*" },
   {
    "name": "if_octets",
    "query": "collectd.$host.$server.$interface.*"
   },
   { "name": "memory", "query": "collectd.$host.$server.*" },
   { "name": "swap", "query": "collectd.$host.$server.*.*" },
   { "name": "compute", "query": "collectd.*" },
   { "name": "uuid", "query": "collectd.$compute.*" },
   { "name": "virt", "query": "collectd.$compute.$uuid.*" },
   { "name": "vcpu", "query": "collectd.$host.$uuid.$virt.*" }
  ]
 },
 "panels": [
  {
   "title": "virt-memory-avg1h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(summarize(collectd.$compute.$uuid.$virt.memory-usable, '1h', 'avg', true), 'memory-usable')"
    }
   ]
  },
  {
   "title": "network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$host.$server.$interface.$if_octets.rx, 'Data In')"
    },
    {
     "target": "alias(collectd.$host.$server.$interface.$if_octets.tx, 'Data Out')"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$host.$server.$cpu.cpu-user, 'cpu-user')"
    },
    {
     "target": "alias(collectd.$host.$server.$cpu.cpu-idle, 'cpu-idle')"
    },
    {
     "target": "alias(collectd.$host.$server.$cpu.cpu-system, 'cpu-system')"
    },
    {
     "target": "alias(collectd.$host.$server.$cpu.cpu-wait, 'cpu-wait')"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$host.$server.$memory.memory-used, 'memory_used')"
    }
   ]
  }
 ]
}