{
 "title": "Summarizes VMs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "compute", "query": "collectd.*" },
   { "name": "uuid", "query": "collectd.$compute.*" },
   { "name": "virt", "query": "collectd.$compute.$uuid.*" },
   {
    "name": "vcpu",
    "query": "collectd.$compute.$uuid.$virt.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Ram Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(summarize(collectd.$compute.$uuid.$virt.memory-usable, '1h', 'avg', false), 'Ram Used')"
    }
   ]
  },
  {
   "title": "Average Percent Ram Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(summarize(scale(divideSeries(#A, #C), 100), '1h', 'avg', false), 'Ram Used')",
     "targetFull": "alias(summarize(scale(divideSeries(collectd.$compute.$uuid.$virt.memory-usable, collectd.$compute.$uuid.$virt.memory-total), 100), '1h', 'avg', false), 'Ram Used')"
    }
   ]
  },
  {
   "title": "Average CPU Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(summarize(collectd.$compute.$uuid.$virt.virt_cpu_total, '1h', 'avg', false), 'CPU Used')"
    }
   ]
  },
  {
   "title": "Average Percent CPU Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(summarize(collectd.$compute.$uuid.$virt.percent-virt_cpu_total, '1h', 'avg', false), 'CPU Used')"
    }
   ]
  }
 ]
}