{
 "title": "VMs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "compute", "query": "collectd.*" },
   { "name": "uuid", "query": "collectd.$compute.*" },
   { "name": "virt", "query": "collectd.$compute.$uuid.*" },
   {
    "name": "interface",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "diskrw",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "diskops",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "vcpu",
    "query": "collectd.$compute.$uuid.$virt.*"
   }
  ]
 },
 "panels": [
  {
   "title": "RAM free",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(divideSeries(#A, #B), 100)",
     "targetFull": "scale(divideSeries(collectd.$compute.$uuid.$virt.memory-unused, collectd.$compute.$uuid.$virt.memory-total), 100)"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(scale(divideSeries(#A, #B), 100), 'Used')",
     "targetFull": "alias(scale(divideSeries(collectd.$compute.$uuid.$virt.virt_cpu_total, scale(sumSeries(offset(scale(collectd.$compute.$uuid.$virt.$vcpu, 0), 1)), 1000000000)), 100), 'Used')"
    }
   ]
  },
  {
   "title": "Network $uuid",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$interface.tx, 'Data Out')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$interface.rx, 'Data In')"
    }
   ]
  },
  {
   "title": "DISK R/W $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskrw.read, 'read')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskrw.write, 'write')"
    }
   ]
  },
  {
   "title": "DISK IOPS $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskops.read, 'read')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskops.write, 'write')"
    }
   ]
  }
 ]
}