{
 "title": "VMs",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "compute", "query": "collectd.*" },
   { "name": "uuid", "query": "collectd.$compute.*" },
   { "name": "virt", "query": "collectd.$compute.$uuid.*" },
   {
    "name": "interface",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "diskrw",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "diskops",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "vcpu",
    "query": "collectd.$compute.$uuid.$virt.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory unused",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "alias(summarize(collectd.$compute.$uuid.$virt.memory-unused, '1h', 'sum', false), 'sum 1h')"
    }
   ]
  },
  {
   "title": "Network $virt",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$interface.tx, 'Data Out')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$interface.rx, 'Data In')"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByNode(collectd.$compute.$uuid.$virt.percent-virt_cpu_total, 4, 3)"
    }
   ]
  },
  {
   "title": "DISK IOPS $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskops.read, 'read')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskops.write, 'write')"
    }
   ]
  },
  {
   "title": "Ram Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(#A, 1e-9), 4, 3)",
     "targetFull": "aliasByNode(scale(collectd.$compute.$uuid.$virt.memory-unused, 1e-9), 4, 3)"
    }
   ]
  },
  {
   "title": "DISK R/W $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskrw.read, 'read')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskrw.write, 'write')"
    }
   ]
  }
 ]
}