{
 "title": "VMs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "compute", "query": "collectd.*" },
   { "name": "uuid", "query": "collectd.$compute.*" },
   { "name": "virt", "query": "collectd.$compute.$uuid.*" },
   {
    "name": "interface",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "diskrw",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "diskops",
    "query": "collectd.$compute.$uuid.$virt.*"
   },
   {
    "name": "vcpu",
    "query": "collectd.$compute.$uuid.$virt.*"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.$compute.$uuid.$virt.percent-virt_cpu_total"
    },
    {
     "target": "alias(scale(divideSeries(#B, #C), 100), 'Used ')",
     "targetFull": "alias(scale(divideSeries(collectd.$compute.$uuid.$virt.virt_cpu_total, scale(sumSeries(offset(scale(collectd.$compute.$uuid.$virt.$vcpu, 0), 1)), 1000000000)), 100), 'Used ')"
    }
   ]
  },
  {
   "title": "Network $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$interface.tx, 'Data Out')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$interface.rx, 'Data In')"
    }
   ]
  },
  {
   "title": "DISK IOPS $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskops.read, 'read')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskops.write, 'write')"
    }
   ]
  },
  {
   "title": "Ram Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "scale(#A, 0.000000001)",
     "targetFull": "scale(collectd.$compute.$uuid.$virt.memory-unused, 0.000000001)"
    }
   ]
  },
  {
   "title": "DISK R/W $uuid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskrw.read, 'read')"
    },
    {
     "target": "alias(collectd.$compute.$uuid.$virt.$diskrw.write, 'write')"
    }
   ]
  }
 ]
}