#!/usr/bin/python3.5

factory_settings['check_mk_memory_free_default_value'] = {
    'config': ((None, None), False),
}

def inventory_check_mk_memory_free(info):
    for line in info:
        line = " ".join(line)
        line = str(line)
        data = line.split(':')
        check_mk_memory_free_item = "Memory service: " + str(data[0])
        yield (check_mk_memory_free_item, "check_mk_memory_free_default_value")

def check_mk_memory_free(item, params, info):
    print (item, params, info)
    hostinfo_in_item=''
    if ":" in item:
        item_as_list = item.split(": ")
        host_in_item, hostinfo_in_item = item_as_list
    else:
        hostinfo_in_item = item
     
    for line in info:
        line = " ".join(line) 
        if ":" in line:
            line_as_list = line.split(': ')
            line_as_list[1] = line_as_list[1].split(' ')
            print(line_as_list)
    
    percent = 100 - float(line_as_list[1][3])
    state = 3
    total = 100
    if percent >= 20:
        state = 0
    elif percent >= 10:
        state = 1
    elif percent < 10:
        state = 2
    return state, "{} : {}".format(hostinfo_in_item, " ".join(line_as_list[1])), [(state, percent, total)]

# check_mk_info la ten cua plugin
check_info ["check_mk_memory_free"] = {
    'default_levels_variable': "check_mk_memory_free_default_value",
    'inventory_function': inventory_check_mk_memory_free,
    'check_function': check_mk_memory_free,
    'service_description': 'CheckMK info',
    'has_perfdata': True,
    'group': "check_mk_info",
}
